---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBA6wLIsulU4u92MRi3r2G7pAa1iuXfk6fwB9TCFGMeOwv7a50x7ddW8b7uJFvehKDHwenIYFg2uvSUHujggHq0////TcDTzekILTaYMlpxNkClmBYRhU/S/zgUgdt8R4MKpLAvPAm/5LUM3Q5RrI6r0QjoncZsN1dj2eE9X6MmJwptr+s6yON11Jc43JW/m9Mk/jkdL0OY30bXj8vdP/sCdw7wwL4jApktfjNb3r9FscN+xN2ldV0luI9/ZLXY1y4H17dnvxDlysmXNcNG35QW/ComuznHuRMIVnlij8nlk1/mEqsswgb+WpHkHotiHv+4YylCvuMoOAyQY+SODWSnoAwT/DKr4RneyyQREe/fMkVfowq/48iBW09UKHROWYCkOKQvzvEyWrf39lYoG98M+hwRuonyLdJGWhrp8AeXvsb1NLiHmAQgi5lPfxN9oicP+R6gDVMIpdfwwjBnfstV9Aiw1artrskhWfPojb/2iPStkrv7mLLgh82N8VUzhlbNKnn678yswPlHdee7a7r3VfUatq5r4BSfWn4QwRbJHl16rKAMCZqDN9qMIVcd7I5jSr/Kbur/PJTbSTMdMHHF4Ug5Mid8x3CqMNzlJ2EG4gZcfbCKlolyLTeY0NFhVb+CnXwgs65ql9Dc2p42yTInEhJ4lpDM1dZYASl3yBNXGEkptaZf2b+Qwc+eabPhlwtic+C0uDZADlPfB+Hq0e+WYPzWIcr9vtA6P622kEcl4LoPP5c1O40ZZeAhwyhgs3mhyw==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
